<?php
class Count extends CI_Controller

{
    function __construct()
    {
        parent::__construct();
        $this->load->model('count_model');
        $this->load->library('session');
        $this->load->library('form_validation');
        $this->load->library('encrypt');
        $this->load->helper('form');
        $this->load->helper('url');
        $this->load->helper('cookie');
    }

    public function index()
    {
echo "□営業■営業"."<br />";
    $this->count_model->count("http://u-note.me/category/sales",29);
echo "□営業■戦略"."<br />";
    $this->count_model->count("http://u-note.me/category/sales/strategy",10);
echo "□営業■トーク"."<br />";
    $this->count_model->count("http://u-note.me/category/sales/talk",7);
echo "□営業■メール"."<br />";
    $this->count_model->count("http://u-note.me/category/sales/email",4);
echo "□営業■電話"."<br />";
    $this->count_model->count("http://u-note.me/category/sales/telephone",3);
echo "□営業■手紙"."<br />";
    $this->count_model->count("http://u-note.me/category/sales/letter",2);
echo "□営業■ノルマ"."<br />";
    $this->count_model->count("http://u-note.me/category/sales/quota",2);
echo "□営業■辛い・辞めたい"."<br />";
    $this->count_model->count("http://u-note.me/category/sales/hardships",3);
echo "□営業■ツール"."<br />";
    $this->count_model->count("http://u-note.me/category/sales/tool",5);
echo "□営業■髪型"."<br />";
    $this->count_model->count("http://u-note.me/category/sales/hair",1);
echo "□営業■スーツ・ネクタイ"."<br />";
    $this->count_model->count("http://u-note.me/category/sales/suit",6);
echo "□営業■カバン・靴"."<br />";
    $this->count_model->count("http://u-note.me/category/sales/bag",3);
echo "□営業■クロージング"."<br />";
    $this->count_model->count("http://u-note.me/category/sales/closing",2);
echo "□営業■目標・売上"."<br />";
    $this->count_model->count("http://u-note.me/category/sales/target",4);
echo "□営業■給料・インセンティブ"."<br />";
    $this->count_model->count("http://u-note.me/category/sales/salary",2);
echo "□営業■資料"."<br />";
    $this->count_model->count("http://u-note.me/category/sales/material",2);
echo "□営業■心得"."<br />";
    $this->count_model->count("http://u-note.me/category/sales/knowledge",10);
echo "□企画・マーケティング■企画・マーケティング"."<br />";
    $this->count_model->count("http://u-note.me/category/marketing",29);
echo "□企画・マーケティング■事例"."<br />";
    $this->count_model->count("http://u-note.me/category/marketing/case",2);
echo "□企画・マーケティング■戦略・手法"."<br />";
    $this->count_model->count("http://u-note.me/category/marketing/strategy",21);
echo "□企画・マーケティング■資格・スキル"."<br />";
    $this->count_model->count("http://u-note.me/category/marketing/skills",6);
echo "□企画・マーケティング■アイデア"."<br />";
    $this->count_model->count("http://u-note.me/category/marketing/idea",7);
echo "□企画・マーケティング■資料"."<br />";
    $this->count_model->count("http://u-note.me/category/marketing/data",7);
echo "□経営・起業■経営・起業"."<br />";
    $this->count_model->count("http://u-note.me/category/business",29);
echo "□経営・起業■起業家"."<br />";
    $this->count_model->count("http://u-note.me/category/business/entrepreneur",16);
echo "□経営・起業■シリコンバレー"."<br />";
    $this->count_model->count("http://u-note.me/category/business/silicon-valley",3);
echo "□経営・起業■経営戦略・方法"."<br />";
    $this->count_model->count("http://u-note.me/category/business/strategy",14);
echo "□経営・起業■マネジメント"."<br />";
    $this->count_model->count("http://u-note.me/category/business/management",22);
echo "□経営・起業■起業資金"."<br />";
    $this->count_model->count("http://u-note.me/category/business/capital",3);
echo "□経営・起業■事業計画"."<br />";
    $this->count_model->count("http://u-note.me/category/business/plan",3);
echo "□経営・起業■経営指標"."<br />";
    $this->count_model->count("http://u-note.me/category/business/index",2);
echo "□経営・起業■経営革新"."<br />";
    $this->count_model->count("http://u-note.me/category/business/improvement",2);
echo "□経営・起業■起業アイディア"."<br />";
    $this->count_model->count("http://u-note.me/category/business/idea",3);
echo "□経営・起業■組織"."<br />";
    $this->count_model->count("http://u-note.me/category/business/organization",43);
echo "□経営・起業■独立・フリーランス"."<br />";
    $this->count_model->count("http://u-note.me/category/business/freelance",4);
echo "□経営・起業■会社設立・起業準備"."<br />";
    $this->count_model->count("http://u-note.me/category/business/establish",8);
echo "□Web・インターネット■Web・インターネット"."<br />";
    $this->count_model->count("http://u-note.me/category/internet",29);
echo "□Web・インターネット■アプリ事例"."<br />";
    $this->count_model->count("http://u-note.me/category/internet/apps",6);
echo "□Web・インターネット■サービス事例"."<br />";
    $this->count_model->count("http://u-note.me/category/internet/service",16);
echo "□Web・インターネット■ソーシャルメディア"."<br />";
    $this->count_model->count("http://u-note.me/category/internet/sns",13);
echo "□Web・インターネット■SEO"."<br />";
    $this->count_model->count("http://u-note.me/category/internet/seo",3);
echo "□Web・インターネット■プロデューサー・ディレクター"."<br />";
    $this->count_model->count("http://u-note.me/category/internet/producer",2);
echo "□Web・インターネット■エンジニア"."<br />";
    $this->count_model->count("http://u-note.me/category/internet/engineer",5);
echo "□Web・インターネット■デザイナー"."<br />";
    $this->count_model->count("http://u-note.me/category/internet/designer",3);
echo "□ビジネスマナー■ビジネスマナー"."<br />";
    $this->count_model->count("http://u-note.me/category/manner",29);
echo "□ビジネスマナー■メール"."<br />";
    $this->count_model->count("http://u-note.me/category/manner/email",7);
echo "□ビジネスマナー■電話"."<br />";
    $this->count_model->count("http://u-note.me/category/manner/telephone",4);
echo "□ビジネスマナー■手紙"."<br />";
    $this->count_model->count("http://u-note.me/category/manner/letter",4);
echo "□ビジネスマナー■飲み会"."<br />";
    $this->count_model->count("http://u-note.me/category/manner/party",5);
echo "□ビジネスマナー■結婚式"."<br />";
    $this->count_model->count("http://u-note.me/category/manner/wedding",2);
echo "□ビジネスマナー■葬式"."<br />";
    $this->count_model->count("http://u-note.me/category/manner/funeral",2);
echo "□ビジネスマナー■年賀状・寒中見舞い"."<br />";
    $this->count_model->count("http://u-note.me/category/manner/new-year-message",1);
echo "□ビジネスマナー■お中元・暑中見舞い"."<br />";
    $this->count_model->count("http://u-note.me/category/manner/mid-year-message",2);
echo "□ビジネスマナー■お歳暮"."<br />";
    $this->count_model->count("http://u-note.me/category/manner/year-end-gift",1);
echo "□ビジネスマナー■挨拶"."<br />";
    $this->count_model->count("http://u-note.me/category/manner/greeting",8);
echo "□ビジネスマナー■名刺"."<br />";
    $this->count_model->count("http://u-note.me/category/manner/card",5);
echo "□ビジネスマナー■エレベーター・エスカレーター"."<br />";
    $this->count_model->count("http://u-note.me/category/manner/elevator",2);
echo "□ビジネスマナー■歓迎会・送別会"."<br />";
    $this->count_model->count("http://u-note.me/category/manner/welcome",4);
echo "□ビジネスマナー■ミーティング・会議"."<br />";
    $this->count_model->count("http://u-note.me/category/manner/meeting",4);
echo "□ビジネスマナー■上司・部下"."<br />";
    $this->count_model->count("http://u-note.me/category/manner/relationship",27);
echo "□ビジネスマナー■バレンタインデー・ホワイトデー"."<br />";
    $this->count_model->count("http://u-note.me/category/manner/valentine",2);
echo "□プレゼン■プレゼン"."<br />";
    $this->count_model->count("http://u-note.me/category/presentation",29);
echo "□プレゼン■スライド・資料"."<br />";
    $this->count_model->count("http://u-note.me/category/presentation/slide",7);
echo "□プレゼン■テクニック・コツ"."<br />";
    $this->count_model->count("http://u-note.me/category/presentation/skill",9);
echo "□プレゼン■構成・流れ"."<br />";
    $this->count_model->count("http://u-note.me/category/presentation/construction",3);
echo "□プレゼン■テーマ"."<br />";
    $this->count_model->count("http://u-note.me/category/presentation/theme",2);
echo "□プレゼン■話し方"."<br />";
    $this->count_model->count("http://u-note.me/category/presentation/locution",3);
echo "□プレゼン■準備・練習"."<br />";
    $this->count_model->count("http://u-note.me/category/presentation/preparation",2);
echo "□プレゼン■英語"."<br />";
    $this->count_model->count("http://u-note.me/category/presentation/english",4);
echo "□プレゼン■PowerPoint・Keynote"."<br />";
    $this->count_model->count("http://u-note.me/category/presentation/powerpoint",3);
echo "□プレゼン■iPad・アプリ"."<br />";
    $this->count_model->count("http://u-note.me/category/presentation/ipad",2);
echo "□プレゼン■図・グラフ・イラスト"."<br />";
    $this->count_model->count("http://u-note.me/category/presentation/graph",2);
echo "□キャリア・転職・就職■キャリア・転職・就職"."<br />";
    $this->count_model->count("http://u-note.me/category/career",29);
echo "□キャリア・転職・就職■キャリアアップ"."<br />";
    $this->count_model->count("http://u-note.me/category/career/career-enhancement",88);
echo "□キャリア・転職・就職■資格・スキル"."<br />";
    $this->count_model->count("http://u-note.me/category/career/skill",45);
echo "□キャリア・転職・就職■英語"."<br />";
    $this->count_model->count("http://u-note.me/category/career/english",26);
echo "□キャリア・転職・就職■面接"."<br />";
    $this->count_model->count("http://u-note.me/category/career/interview",19);
echo "□キャリア・転職・就職■履歴書"."<br />";
    $this->count_model->count("http://u-note.me/category/career/curricula-vitae",3);
echo "□キャリア・転職・就職■志望動機"."<br />";
    $this->count_model->count("http://u-note.me/category/career/reasons-for-applying",3);
echo "□キャリア・転職・就職■自己アピール"."<br />";
    $this->count_model->count("http://u-note.me/category/career/self-appeal",3);
echo "□総務・経理・人事■総務・経理・人事"."<br />";
    $this->count_model->count("http://u-note.me/category/admin",29);
echo "□総務・経理・人事■採用"."<br />";
    $this->count_model->count("http://u-note.me/category/admin/adoption",4);
echo "□総務・経理・人事■会計・経理"."<br />";
    $this->count_model->count("http://u-note.me/category/admin/accounting",2);
echo "□総務・経理・人事■税務"."<br />";
    $this->count_model->count("http://u-note.me/category/admin/taxation-business",3);
echo "□総務・経理・人事■労務"."<br />";
    $this->count_model->count("http://u-note.me/category/admin/labor",3);
echo "□総務・経理・人事■法務"."<br />";
    $this->count_model->count("http://u-note.me/category/admin/legal-affairs",2);


    }
        
}